### PR TITLE
Update model-guide.rst

### PR DESCRIPTION
**Pull request by 4er4er4er**
I am revising the modeling guide written by Gleb for MP-based solvers, based on updated categories that I developed for recent talks. I have already made some changes to the develop branch, but has become clear that continuing in that way would leave the guide potentially in a confusing state for a few weeks; thus I am working in a different branch from this point onward.

### CODE REVIEW

**Comment by glebbelov** [comment]
Both commits on model-guide.rst look fine to me.

**Review by glebbelov — COMMENTED** [review]
Both commits on model-guide.rst look fine to me. Note that the 1st commit, being on the develop branch, is already online at amplmp.readthedocs.io.

If possible, let's avoid long-lived branches. In any case, let's merge regularly both ways, earlier = better.

**Review by glebbelov — APPROVED** [review]

**Comment by 4er4er4er** [comment]
I am going to make some revisions now to the syntax terminology in the update branch (AMPL-MP-Modeling-Guide-Revised). This will temporarily cause some inconsistencies, so I won't make further commits until these revisions are done.

**Review by glebbelov — APPROVED** [review]

**Review by glebbelov — APPROVED** [review]

**Review by gomfy — APPROVED** [review]

**Review by gomfy — COMMENTED** [review]
-   Under **Expressions supported** section, the sentences regarding extensions:
    How about introducing some bullet points? For example,
    > MP automatically enables extension, which support:
    > - conditional, logical, or counting operators,
    > - model transformations between equivalent problem classes (e.g. quadratic to linear),
    > - native solver extensions. 
    
    Regarding extensions handled by AMPL, are those not handled by MP? If not, then I think it would be useful to mention that.
-   Under **Expressions supported** section/**constr** bullet point:
    There is an **on** missing after **depending**. The sentence should read:
    > represents a constraint of the model, which may evaluate to true or false depending **on** the values of variables that it contains.
-   Under **Expressions supported** section, last sentence:
    How about rephrasing it like below?
    > AMPL represents these as expression trees, which are sent to MP-based solver interfaces to be processed as required by the underlying solver.

**Review by glebbelov — APPROVED** [review]

**Pull request merged**
