### PR TITLE
Added support for values list to backend.h

### PR DESCRIPTION
**Pull request by mapgccv**
Added qualifiedName to all options; this allows users to specify options by either their normal and their fully qualified name (e.g. limits:timelimit). This will allow for a better categorization of options by keeping existing scripts compatible.
Also it improves usability by allowing to print only the options in a given namespace (to be implemented yet).
@glebbelov  Any feedback?

### CODE REVIEW

**Comment by glebbelov** [comment]
Overall fine, with small remarks see below.

Major: there is a question of synonyms: e.g., ASL Gurobi has ams_mode and poolmode (and gurobidirect calls it [sol:]pool_mode), do we want to keep them as synonyms? Then it can be either as separate options, or we could allow the specification of an option to contain several keys, e.g. AddSolverOption("pool_mode sol:pool_mode ams_mode poolmode", .....).

I am for the former way, have them as separate options, possibly having a new object OptionSynonym which refers to an existing option but has a different description.

Minor:
- gecode.cc: outfreq was aliased as gen:outlev...
- many options which are now categorized as gecode:, could be cp: or even something more general like search:
- finally, OptionNameLess::operator() is buggy I think, the return in 486. And printf()

**Comment by glebbelov** [comment]
... and, another point: is ever any option going to have <name1> and <class>:<name2> with name1 != name2? If not, things could simplify..

**Comment by mapgccv** [comment]
Regarding the major point:
you have good quite a point here; my idea would be to try to keep the synonyms at a minimum but we may be in the position where they are inevitable. I think I got the reason behind the multiple naming in this case:
ASL_gurobi has:
* **poolmode** that is similar to the name in the gurobi API (PoolSearchModel) therefore useful for gurobi users
* **ams_mode** that is Dave's take on grouping options into underscore-separated namespaces
and then mp has its own.
So, although I'd rather not have synonyms, they are probably here to stay. Indeed I agree with your solution of having some simplified object (OptionSynonom) which will have a name, a "main option name" and an (automated?) description saying: "refer to main option name". I think it will just be a matter of modifying the "FindOption" function to accomodate this.

On the minor points:
* gecode.cc: outfreq was aliased as gen:outlev... _Well spotted, fixed in the last commit_
* many options which are now categorized as gecode:, could be cp: or even something more general like search. _Agreed, those were temp classifications just to have it compiling_
* OptionNameLess::operator() is buggy I think, the return in 486. And printf(). _Indeed, it was just a rushed commit because I had to leave but wanted to start this discussion first. I have now scrapped all the modifications to the OptionNameLess struct, and implemented the proper find option logic in "find option"._
* is ever any option going to have and : with name1 != name2? If not, things could simplify. _I am not 100% sure, I think we might, if we want to "suggest" users to move to a different numenclature_

**Comment by glebbelov** [comment]
I just thought changing the interface of AddOption() breaks the API. ilogcp, cplexdirect, LocalSolver don't compile. I've heard about some external people using MP for new solvers. We have to stick with the existing API and only extend it.

Suggest the following way.

`Add.....Option( "lim:time timelim", "description", ... )
`

creates an option listed in -= as

```
lim:time (timelim)
        bla bla
```

I'll have a go. Maybe even to allow several 'inline synonyms'

**Comment by mapgccv** [comment]
> I just thought changing the interface of AddOption() breaks the API. ilogcp, cplexdirect, LocalSolver don't compile. I've heard about some external people using MP for new solvers. We have to stick with the existing API and only extend it.
> 
> Suggest the following way.
> 
> `Add.....Option( "lim:time timelim", "description", ... ) `
> 
> creates an option listed in -= as
> 
> ```
> lim:time (timelim)
>         bla bla
> ```
> 
> I'll have a go. Maybe even to allow several 'inline synonyms'

Makes sense, I broke the API "intentionally" to develop the new infrastructure; the idea was to then add overloads not requiring the "qualifiedName"; your idea is better though, I think, as it gives us more freedom and requires no API changes altogether. Are you working on it or shall I?

**Comment by glebbelov** [comment]
Almost ready, tests passing, about to commit

**Comment by glebbelov** [comment]
Pushed. Feedback?

**Comment by mapgccv** [comment]
Do we still need `SolverOptionSynonym`? Or, in other words, what will be the relation between an inline synonym and an independent one?

Just one thing, more for future planning than related to the changes themselves: I think it would be nice to have a couple of options related to the "-=" option:
0. "normal view": `name (inlinesyn1 inlinesyn2       inlinesynn):
1. "compatibility view": with the options listed as in the ASL driver (no namespaces) `inlinysyn1'
2. "namespace view": ordered by namespace
3. "namespace filtered": only the option in the specified namespace

This would necessitate retaining some meta information regarding which in the list of names is what. But I guess we can work with conventions:
```AddOption("name1 [name2] ... [namen]", ...)```  where ::

name1=qualified name
name2=ASL name
....
namen=(n-2)th synonym

At this point, my point 3 above could actually be achieved simply by filtering the options list by any string; if the string contains a colon it will automatically have the effect of filtering by namespace.

**Comment by glebbelov** [comment]
I think OptionSynonym is fine for now, to facilitate finding old names. When we have ASL sorting, it is less necessary.

For sorting, Option 3 is just by using grep. Option 2 is already default. Option 1 can be made by changing the inline_synonyms_ to be a vector and using the 1st element (or just the primary name if none), for example by method name_ASL().

You created the request as to merge into master. Do you want to change it to merge into feature/direct_intf? Or close the request and merge manually. Note that I already merged feature/direct into this branch. Or let me know if I should do it. Also, working on the master as main branch is thinkable if good for any reason, but I'd prefer working on the feature and updating master just sometimes.

**Pull request closed without merging**
