### PR TITLE
Extract variable types and objective information

### PR DESCRIPTION
**Pull request by dpo**
See https://github.com/dpo/AmplNLReader.jl/issues/10.

### CODE REVIEW

**Comment by mlubin** [comment]
:+1:

**Comment by vitaut** [comment]
Merged, thanks!

**Comment by mlubin** [comment]
Was it intended to merge into the 2.0 branch? Should also get into master.

**Comment by dpo** [comment]
The PR into `master` wasn't clean. That's why I branched `2.0`.

**Comment by dpo** [comment]
@vitaut It seems like this never made it into 3.0.0.

**Comment by vitaut** [comment]
@dpo Should be fixed now, thanks.

**Pull request merged**
